# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 10:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='applicant_is',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='blood_group',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='bride_for_job',
            field=models.CharField(choices=[(0, 'Need'), (1, 'Need not go for job')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='bride_forced',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='brief_information',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='colour',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='contact_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='date_of_birth',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='doing_business',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='education',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='education_bride',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='email_address',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='employment_details',
            field=models.CharField(choices=[(0, 'Central Govt'), (1, 'Central Govt. Undertaking'), (2, 'State Govt.'), (3, 'State Govt. Undertaking'), (4, 'Private'), (5, 'Self Employee'), (6, '(MNC(India))'), (7, '(MNC(Abroad))')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='family_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='father_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='gothram',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='having_house',
            field=models.CharField(choices=[(0, 'Own House'), (1, 'Rented House')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='height',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='height_shld_be',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='horoscope',
            field=models.CharField(choices=[(0, 'Match is must'), (1, 'Mutual acceptance will also hold good')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='languages_known',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='living_in',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='marital_status',
            field=models.CharField(choices=[(0, 'Never Married'), (1, 'Divorcee'), (3, 'Widow/Widower')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mobile',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_f_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='mother_name',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='natchathram',
            field=models.CharField(choices=[(0, 'Aswini'), (1, 'Bharani'), (2, 'Karthigai'), (3, 'Rohini'), (4, 'Mrigasheersham'), (5, 'Thiruvaathirai'), (6, 'Punarpoosam'), (7, 'Poosam'), (8, 'Aayilyam'), (9, 'Makam'), (10, 'Pooram'), (11, 'Uthiram'), (12, 'Hastham'), (13, 'Chithirai'), (14, 'Swaathi'), (15, 'Visaakam'), (16, 'Anusham'), (17, 'Kettai'), (18, 'Moolam'), (19, 'Pooraadam'), (20, 'Uthiraadam'), (21, 'Thiruvonam'), (22, 'Avittam'), (23, 'Chathayam/Sadayam'), (24, 'Poorattathi'), (25, 'Uthirattathi'), (26, 'Revathi')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='need',
            field=models.CharField(choices=[(0, 'Never Married'), (1, 'Divorcee'), (2, 'Widow/widower')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='office_address',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='origin',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='origin_place',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='phone',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='place',
            field=models.CharField(default=11, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='rasi',
            field=models.CharField(choices=[(0, 'MESHAM'), (1, 'MITHUNAM'), (2, 'KANNI'), (3, 'KUMBAM'), (4, 'MEENAM'), (5, 'SIMMAM'), (6, 'TULAM'), (7, 'VIRUCHIGAM'), (8, 'THANUSU'), (9, 'MAKARAM'), (10, 'RISHABAM'), (11, 'KADAGAM')], default=1, max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='salary',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='time',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='application',
            name='working_in',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='application',
            name='padam',
            field=models.CharField(choices=[(0, '1'), (1, '2'), (2, '3'), (3, '4')], max_length=2),
        ),
    ]
