# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2018-03-24 13:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matrimony', '0002_auto_20180324_1042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='bride_for_job',
            field=models.CharField(choices=[('Need', 'Need'), ('Need not go for job', 'Need not go for job')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='date_of_birth',
            field=models.DateField(max_length=8),
        ),
        migrations.AlterField(
            model_name='application',
            name='employment_details',
            field=models.CharField(choices=[('Central Govt', 'Central Govt'), ('Central Govt. Undertaking', 'Central Govt. Undertaking'), ('State Govt.', 'State Govt.'), ('State Govt. Undertaking', 'State Govt. Undertaking'), ('Private', 'Private'), ('Self Employee', 'Self Employee'), ('(MNC(India))', '(MNC(India))'), ('(MNC(Abroad))', '(MNC(Abroad))')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='having_house',
            field=models.CharField(choices=[('Own House', 'Own House'), ('Rented House', 'Rented House')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='horoscope',
            field=models.CharField(choices=[('Match is must', 'Match is must'), ('Mutual acceptance will also hold good', 'Mutual acceptance will also hold good')], max_length=50),
        ),
        migrations.AlterField(
            model_name='application',
            name='marital_status',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Divorcee', 'Divorcee'), ('Widow/Widower', 'Widow/Widower')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='natchathram',
            field=models.CharField(choices=[('Aswini', 'Aswini'), ('Bharani', 'Bharani'), ('Karthigai', 'Karthigai'), ('Rohini', 'Rohini'), ('Mrigasheersham', 'Mrigasheersham'), ('Thiruvaathirai', 'Thiruvaathirai'), ('Punarpoosam', 'Punarpoosam'), ('Poosam', 'Poosam'), ('Aayilyam', 'Aayilyam'), ('Makam', 'Makam'), ('Pooram', 'Pooram'), ('Uthiram', 'Uthiram'), ('Hastham', 'Hastham'), ('Chithirai', 'Chithirai'), ('Swaathi', 'Swaathi'), ('Visaakam', 'Visaakam'), ('Anusham', 'Anusham'), ('Kettai', 'Kettai'), ('Moolam', 'Moolam'), ('Pooraadam', 'Pooraadam'), ('Uthiraadam', 'Uthiraadam'), ('Thiruvonam', 'Thiruvonam'), ('Avittam', 'Avittam'), ('Chathayam/Sadayam', 'Chathayam/Sadayam'), ('Poorattathi', 'Poorattathi'), ('Uthirattathi', 'Uthirattathi'), ('Revathi', 'Revathi')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='need',
            field=models.CharField(choices=[('Never Married', 'Never Married'), ('Divorcee', 'Divorcee'), ('Widow/widower', 'Widow/widower')], max_length=20),
        ),
        migrations.AlterField(
            model_name='application',
            name='padam',
            field=models.CharField(choices=[('0', '1'), ('1', '2'), ('2', '3'), ('3', '4')], max_length=2),
        ),
        migrations.AlterField(
            model_name='application',
            name='rasi',
            field=models.CharField(choices=[('MESHAM', 'MESHAM'), ('MITHUNAM', 'MITHUNAM'), ('KANNI', 'KANNI'), ('KUMBAM', 'KUMBAM'), ('MEENAM', 'MEENAM'), ('SIMMAM', 'SIMMAM'), ('TULAM', 'TULAM'), ('VIRUCHIGAM', 'VIRUCHIGAM'), ('THANUSU', 'THANUSU'), ('MAKARAM', 'MAKARAM'), ('RISHABAM', 'RISHABAM'), ('KADAGAM', 'KADAGAM')], max_length=20),
        ),
    ]
